document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("<link rel=\'stylesheet\' type=\'text/css\' href=\'css/login2.css\'>");
document.writeln("<link href=\'css/bootstrap.min.css\' rel=\'stylesheet\'>");
document.writeln("    <style>");
document.writeln("        .firstType{");
document.writeln("");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("<script type=\'text/javascript\' src=\'js/jquery-1.8.3.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'js/bootstrap.js\'></script>");
document.writeln("<title>头部</title>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("	$(function(){");
document.writeln("	    // 判断是否是已经登录的用户");
document.writeln("	    $.ajax({");
document.writeln("            type:\'get\',");
document.writeln("            async:true,");
document.writeln("            url:\'api/v1/user/isLogin.do\',");
document.writeln("            success:function(data) {");
document.writeln("                if (data.code == 1000) {");
document.writeln("                    $(\'#logined\').attr(\'hidden\',false);");
document.writeln("                    $(\'#notLogin\').attr(\'hidden\',true);");
document.writeln("                    $(\'#userInfo\').text(data.data[0].name);");
document.writeln("");
document.writeln("                } else {");
document.writeln("                    $(\'#logined\').attr(\'hidden\',true);");
document.writeln("                    $(\'#notLogin\').attr(\'hidden\',false);");
document.writeln("                }");
document.writeln("            }");
document.writeln("        })");
document.writeln("        function getLength(obj){");
document.writeln("");
document.writeln("            return Object.key(obj).length;");
document.writeln("        }");
document.writeln("");
document.writeln("");
document.writeln("        // 查询所有的商品的详情");
document.writeln("        $.ajax({");
document.writeln("            type:\'get\',");
document.writeln("            async:true,");
document.writeln("            url:\'api/v1/goods/showAllGoodTypes.do\',");
document.writeln("            success:function(data) {");
document.writeln("                //查询出所有的类型表，然后进行展示");
document.writeln("                var goodsTypeList = data.data;");
document.writeln("");
document.writeln("                // 代表了一级的类型有哪些，存储了{1，数码}");
document.writeln("                var firstType = {};");
document.writeln("                var j = 0;");
document.writeln("                // 代表了一级商品的id{0，1}");
document.writeln("                var typeMap = {};");
document.writeln("");
document.writeln("                for (i = 0; i<goodsTypeList.length;i++) {");
document.writeln("");
document.writeln("                    if (goodsTypeList[i].level == 1) {");
document.writeln("                        firstType[goodsTypeList[i].id]=goodsTypeList[i].name;");
document.writeln("                        typeMap[j] = goodsTypeList[i].id;");
document.writeln("                        j++;");
document.writeln("                    }");
document.writeln("");
document.writeln("                }");
document.writeln("");
document.writeln("");
document.writeln("            j=0;");
document.writeln("                for (i = 0; i<Object.getOwnPropertyNames(firstType).length;i++) {");
document.writeln("");
document.writeln("                    var a = $(\'<a href=\'/getGoodsListByTypeId?typeid=\'+typeMap[i]+\'\'>\'+firstType[typeMap[i]]+\'</a>\');");
document.writeln("                    var ul = $(\'<ul>\')");
document.writeln("                    for (k = 0; k <goodsTypeList.length; k++){");
document.writeln("                        if (goodsTypeList[k].parentid == typeMap[j]) {");
document.writeln("                            var li = $(\'<li class=\'firstType\' style=\'cursor:pointer\'>\');");
document.writeln("                            li.attr(\'name\',goodsTypeList[k].id);");
document.writeln("                            li.text(goodsTypeList[k].name);");
document.writeln("                            ul.append(li);");
document.writeln("                        }");
document.writeln("                    }");
document.writeln("                    var div = $(\'<div style=\'float: left;width: auto\'>\');");
document.writeln("                    div.append(a);");
document.writeln("                    div.append(ul);");
document.writeln("                    $(\'#goodsType\').append(div);");
document.writeln("                    j++;");
document.writeln("                }");
document.writeln("            }");
document.writeln("        })");
document.writeln("        $(\'.firstType\').live(\'click\',function(){");
document.writeln("            var tid = $(this).attr(\'name\');");
document.writeln("            $(\'[name=\'tid\']\').val(tid);");
document.writeln("            alert(2)");
document.writeln("            $(\'#form1\').submit();");
document.writeln("");
document.writeln("        });");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	})");
document.writeln("</script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("				");
document.writeln(" <div id=\'top\'>");
document.writeln("    	<div id=\'topdiv\'>");
document.writeln("            <span>");
document.writeln("                <a href=\'index.jsp\' class=\'a_top\' target=\'_blank\'>锋米之家</a>");
document.writeln("                <li>|</li>");
document.writeln("                <a href=\'\' class=\'a_top\'>锋米之家移动版</a>");
document.writeln("                <li>|</li>");
document.writeln("                <a href=\'\' class=\'a_top\'>问题反馈</a>");
document.writeln("            </span>");
document.writeln("            <span style=\'float:right\' id=\'isLogin\'>");
document.writeln("                    <div id=\'notLogin\' >");
document.writeln("	                <a href=\'login.jsp\' class=\'a_top\'>登录</a>");
document.writeln("	                <li>|</li>");
document.writeln("	                <a href=\'register.jsp\' class=\'a_top\'>注册</a>");
document.writeln("                    </div>");
document.writeln("                    <li>|</li>");
document.writeln("       			<div id=\'logined\' hidden=\'hidden\'>");
document.writeln("                    <a href=\'userAddress?flag=show\' id=\'userInfo\' class=\'a_top\'></a>");
document.writeln("       				<li>|</li>");
document.writeln("       				<a href=\'/api/v1/user/loginout.do\' class=\'a_top\'>注销</a>");
document.writeln("       				<li>|</li>");
document.writeln("                </div>");
document.writeln("       				<a href=\'getOrderList\' class=\'a_top\'>我的订单</a>");
document.writeln("                <li>|</li>");
document.writeln("                <a href=\'\' class=\'a_top\'>消息通知</a>");
document.writeln("                <a href=\'${pageContext.request.contextPath}/getCart\' id=\'shorpcar\'>购物车</a>");
document.writeln("            </span>");
document.writeln("        </div>");
document.writeln(" </div>");
document.writeln("<div id=\'second\'>");
document.writeln("	    <a href=\'\' class=\'seimg\' style=\' margin-top:23px;\'><img id=\'logo\' src=\'image/logo_top.png\' width=\'55\' height=\'54\'/></a>");
document.writeln("        <a href=\'\' class=\'seimg\' style=\' margin-top:17px;\'><img id=\'gif\' src=\'image/yyymix.gif\' width=\'180\' height=\'66\' /></a>");
document.writeln("        <div id=\'goodsType\'>");
document.writeln("			<!-- 根据ajax 回调函数 填写数据 到此id中 -->");
document.writeln("            <!-- Single button -->");
document.writeln("");
document.writeln("        </div>");
document.writeln("    <form id=\'form1\' action=\'/api/v1/goods/showGoodsByType.do\' method=\'get\'>");
document.writeln("        <input type=\'hidden\' name = \'tid\'>");
document.writeln("    </form>");
document.writeln("       <form class=\'form-inline pull-right\' style=\'margin-top: 40px;margin-right: 10px;\'>");
document.writeln("		  <div class=\'form-group\'>");
document.writeln("		    <input type=\'text\' class=\'form-control\' style=\'width: 400px\'  placeholder=\'搜索一下好东西...\'>");
document.writeln("		  </div>");
document.writeln("		  <button type=\'submit\' class=\'btn btn-warning\'><span class=\'glyphicon glyphicon-search\'></span>&nbsp;&nbsp;搜索</button>");
document.writeln("	  </form>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");